[theme]
primaryColor = "#FF6B3B"  # Siklab theme color
backgroundColor = "#FFFFFF"  # Main background color
secondaryBackgroundColor = "#FFF5EB"  # Sidebar background color
textColor = "#000000"  # Dark grey for readability
font = "serif"
base = "light"  # Light theme base